# Generated by Django 5.0.6 on 2025-03-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kid",
            name="role",
            field=models.CharField(
                choices=[("parent", "Parent"), ("kid", "Kid")], default=1, max_length=10
            ),
            preserve_default=False,
        ),
    ]
