# Generated by Django 5.0.6 on 2025-03-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_customuser_parent_alter_child_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="invitation_code",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
