# Generated by Django 4.2 on 2025-03-22 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_locked', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('level', models.IntegerField(default=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='paragraphs/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ENF.category')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('hayawan', 'Hayawan'), ('verb', 'Verb'), ('insan', 'Insan'), ('phrase', 'Phrase'), ('dessin', 'Dessin'), ('test', 'test')], max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='words/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ENF.category')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer_date', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0)),
                ('time_taken', models.FloatField(null=True)),
                ('paragraph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ENF.paragraph')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ENF.word')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('time_taken', models.FloatField(null=True)),
                ('difficulty', models.FloatField(default=0.0)),
                ('paragraph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ENF.paragraph')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ENF.word')),
            ],
        ),
        migrations.CreateModel(
            name='UserCategoryScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ENF.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
