# Generated by Django 5.0.6 on 2025-02-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("lettre", "Lettre"), ("mot", "Mot")], max_length=10
                    ),
                ),
                ("contenu", models.CharField(max_length=50, unique=True)),
                (
                    "audio_url",
                    models.FileField(
                        blank=True, null=True, upload_to="lessons_audios/"
                    ),
                ),
                (
                    "image_url",
                    models.FileField(
                        blank=True, null=True, upload_to="lessons_images/"
                    ),
                ),
            ],
        ),
    ]
