# Generated by Django 5.0.6 on 2025-03-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0004_letter_letterprogress_delete_lettersprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="audios/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transcription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
