# Generated by Django 5.0.6 on 2025-03-05 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0005_audiofile_transcription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="photos/%y/%m/%d")),
            ],
        ),
        migrations.CreateModel(
            name="word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letter", models.CharField(max_length=1, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ENF.category"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AudioFile",
        ),
        migrations.DeleteModel(
            name="Transcription",
        ),
        migrations.AlterField(
            model_name="letterprogress",
            name="letter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ENF.word"
            ),
        ),
        migrations.DeleteModel(
            name="Letter",
        ),
    ]
