# Generated by Django 5.0.6 on 2025-03-05 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0006_category_word_delete_audiofile_delete_transcription_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="photos/%y/%m/%d")),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ENF.category2",
            ),
            preserve_default=False,
        ),
    ]
