# Generated by Django 5.0.6 on 2025-03-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0007_category2_category_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(upload_to="photo/%y/%m/%d"),
        ),
    ]
