# Generated by Django 5.0.6 on 2025-03-06 06:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0008_alter_category_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.RemoveField(
            model_name="category2",
            name="image",
        ),
        migrations.RemoveField(
            model_name="word",
            name="category",
        ),
    ]
