# Generated by Django 5.0.6 on 2025-03-06 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0009_remove_category_image_remove_category2_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ENF.category",
            ),
            preserve_default=False,
        ),
    ]
