# Generated by Django 5.0.6 on 2025-03-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0010_word_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="letter",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
