# Generated by Django 5.0.6 on 2025-03-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0011_alter_word_letter"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_locked",
            field=models.BooleanField(default=True),
        ),
    ]
