# Generated by Django 5.0.6 on 2025-03-08 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0012_category_is_locked"),
    ]

    operations = [
        migrations.RenameField(
            model_name="word",
            old_name="letter",
            new_name="name",
        ),
    ]
