# Generated by Django 5.0.6 on 2025-03-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0014_word_is_correct_word_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="score",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
