# Generated by Django 5.0.6 on 2025-03-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0015_category_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="is_correct",
        ),
        migrations.RemoveField(
            model_name="word",
            name="user",
        ),
        migrations.AddField(
            model_name="wordsprogress",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
    ]
