# Generated by Django 5.0.6 on 2025-03-08 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0017_categoryprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordsprogress",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ENF.word"
            ),
        ),
    ]
