# Generated by Django 5.0.6 on 2025-03-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0018_alter_wordsprogress_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
