# Generated by Django 5.0.6 on 2025-03-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0019_category_category_attempts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category_attempts",
        ),
        migrations.AddField(
            model_name="categoryprogress",
            name="category_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
