# Generated by Django 5.0.6 on 2025-03-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0020_remove_category_category_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="is_drawing",
            field=models.BooleanField(default=False),
        ),
    ]
