# Generated by Django 5.0.6 on 2025-03-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0021_word_is_drawing"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="difficulty",
            field=models.FloatField(default=0.5),
        ),
    ]
