# Generated by Django 5.0.6 on 2025-03-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0022_word_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryprogress",
            name="difficulty",
            field=models.FloatField(default=0.0),
        ),
    ]
