# Generated by Django 5.0.6 on 2025-03-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0023_categoryprogress_difficulty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryprogress",
            name="difficulty",
        ),
        migrations.AddField(
            model_name="wordsprogress",
            name="difficulty",
            field=models.FloatField(default=0.0),
        ),
    ]
