# Generated by Django 5.0.6 on 2025-03-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0024_remove_categoryprogress_difficulty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryprogress",
            name="difficulty",
            field=models.FloatField(default=0.0),
        ),
    ]
