# Generated by Django 5.0.6 on 2025-03-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0025_categoryprogress_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryprogress",
            name="time_taken",
            field=models.FloatField(default=0.0),
        ),
    ]
