# Generated by Django 5.0.6 on 2025-03-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0026_categoryprogress_time_taken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryprogress",
            name="time_taken",
        ),
        migrations.AddField(
            model_name="wordsprogress",
            name="time_taken",
            field=models.FloatField(default=0.0),
        ),
    ]
