# Generated by Django 5.0.6 on 2025-03-10 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0027_remove_categoryprogress_time_taken_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category",
        ),
        migrations.AlterUniqueTogether(
            name="categoryprogress",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="categoryprogress",
            name="category",
        ),
        migrations.RemoveField(
            model_name="categoryprogress",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="letterprogress",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="letterprogress",
            name="letter",
        ),
        migrations.RemoveField(
            model_name="letterprogress",
            name="user",
        ),
        migrations.RemoveField(
            model_name="progression",
            name="utilisateur",
        ),
        migrations.RemoveField(
            model_name="reward",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="wordsprogress",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="wordsprogress",
            name="user",
        ),
        migrations.RemoveField(
            model_name="wordsprogress",
            name="word",
        ),
        migrations.RemoveField(
            model_name="category",
            name="is_locked",
        ),
        migrations.RemoveField(
            model_name="category",
            name="score",
        ),
        migrations.RemoveField(
            model_name="word",
            name="description",
        ),
        migrations.RemoveField(
            model_name="word",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="word",
            name="is_drawing",
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="word",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="words/"),
        ),
        migrations.AddField(
            model_name="word",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="word",
            name="type",
            field=models.CharField(
                choices=[
                    ("hayawan", "Hayawan"),
                    ("verb", "Verb"),
                    ("insan", "Insan"),
                    ("phrase", "Phrase"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="word",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("level", models.IntegerField(default=3)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="paragraphs/"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ENF.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCategoryScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ENF.category"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "category")},
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                ("attempts", models.IntegerField(default=0)),
                ("time_taken", models.FloatField(null=True)),
                ("difficulty", models.FloatField(default=0.0)),
                (
                    "paragraph",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ENF.paragraph",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ENF.word",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Category2",
        ),
        migrations.DeleteModel(
            name="CategoryProgress",
        ),
        migrations.DeleteModel(
            name="LetterProgress",
        ),
        migrations.DeleteModel(
            name="Progression",
        ),
        migrations.DeleteModel(
            name="Reward",
        ),
        migrations.DeleteModel(
            name="WordsProgress",
        ),
    ]
