# Generated by Django 5.0.6 on 2025-03-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0028_remove_category_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=12),
        ),
    ]
