# Generated by Django 5.0.6 on 2025-03-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0029_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
    ]
