# Generated by Django 5.0.6 on 2025-03-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENF", "0030_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_locked",
            field=models.BooleanField(default=True),
        ),
    ]
